// Actual browser executables, opening the same ordinary HTML artifact offline.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium,firefox}=require(process.env.NOVA_PLAYWRIGHT_MODULE||'playwright-core');
(async()=>{const file=path.resolve(process.env.NOVA_HTML_FILE||'/tmp/nova-static-html/frozen-page.html'),out=process.env.NOVA_HTML_RESULTS||'/tmp/nova-static-html';fs.mkdirSync(out,{recursive:true});
const targets=[['Chromium',chromium,{executablePath:process.env.NOVA_USE_PLAYWRIGHT_CHROMIUM?undefined:(process.env.NOVA_CHROMIUM_EXECUTABLE||'/usr/bin/chromium'),args:['--no-sandbox']}]];
if(process.env.NOVA_FIREFOX)targets.push(['Firefox',firefox,{}]);if(process.env.NOVA_EDGE_EXECUTABLE)targets.push(['Edge',chromium,{executablePath:process.env.NOVA_EDGE_EXECUTABLE,args:['--no-sandbox']}]);
const server=require('node:http').createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const local='http://127.0.0.1:'+server.address().port+'/snapshot.html';
const report=[];try{for(const [name,engine,options]of targets){const b=await engine.launch(options);try{let p=await b.newPage();const requests=[],errors=[];p.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(local))requests.push(new URL(r.url()).origin);});p.on('pageerror',e=>errors.push(e.message));let opening='file';try{await p.goto('file://'+file);}catch(e){if(!e.message.includes('ERR_BLOCKED_BY_ADMINISTRATOR'))throw e;opening='localhost: runtime blocks file navigation';await p.close();p=await b.newPage();p.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(local))requests.push(new URL(r.url()).origin);});p.on('pageerror',e=>errors.push(e.message));await p.goto(local);}const text=await p.locator('body').innerText();for(const m of ['Before snapshot marker','TAIL-SNAPSHOT-MARKER','CODE-LAST','TABLE-LAST','中文','café','😀','E=mc^2','LONG-CODE-HEAD','LONG-CODE-TAIL','LONG-TABLE-TAIL'])assert(text.includes(m),name+':'+m);assert(!text.includes('After snapshot marker'));assert(!text.includes('BUTTON-GARBAGE'));assert.equal(await p.locator('script,input,button,nav,iframe').count(),0);assert.deepEqual(requests,[]);assert.deepEqual(errors,[]);assert.equal(await p.locator('img').evaluate(n=>n.naturalWidth),320);await p.screenshot({path:path.join(out,name+'-screen.png')});await p.emulateMedia({media:'print'});assert.equal(await p.locator('body').evaluate(n=>getComputedStyle(n).color),'rgb(0, 0, 0)');assert.equal(await p.locator('pre').first().evaluate(n=>getComputedStyle(n).whiteSpace),'pre-wrap');await p.screenshot({path:path.join(out,name+'-print-css.png')});if(engine===chromium)await p.pdf({path:path.join(out,name+'-desktop.pdf'),preferCSSPageSize:true,printBackground:false});report.push({browser:name,version:b.version(),opening,ordinaryHtml:true,markers:true,imageDecoded:true,noNetworkOrScript:true,printCss:true,pdf:name==='Firefox'?'not-produced':'desktop-only'});}finally{await b.close();}}}finally{server.close();}
fs.writeFileSync(path.join(out,'compatibility.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));})().catch(e=>{console.error(e);process.exitCode=1;});
