package com.example.chatgptnova;

import static org.junit.Assert.*;

import android.content.Context;
import android.database.Cursor;
import androidx.test.platform.app.InstrumentationRegistry;
import com.example.chatgptnova.archive.*;
import java.io.*;
import java.util.UUID;
import org.junit.*;

/** Actual private SQLite/file integration using fictional generated bytes only. */
public final class ArchiveAssetPersistenceTest {
  Context context;

  @Before
  public void before() {
    context = InstrumentationRegistry.getInstrumentation().getTargetContext();
    ArchiveStore.deleteArchive(context);
  }

  @After
  public void after() {
    ArchiveStore.deleteArchive(context);
  }

  File input(boolean malformed) throws Exception {
    File f = File.createTempFile("fictional-assets-", ".zip", context.getCacheDir());
    try (OutputStream out = new FileOutputStream(f)) {
      out.write(ArchiveAssetFixtures.fixture(malformed));
    }
    return f;
  }

  long count(ArchiveStore store, String table) {
    try (Cursor c = store.getReadableDatabase().rawQuery("SELECT COUNT(*) FROM " + table, null)) {
      assertTrue(c.moveToFirst());
      return c.getLong(0);
    }
  }

  @Test
  public void filesReferencesDuplicateAndRestartPersistIndependentlyOfZip() throws Exception {
    File input = input(false);
    String firstSource = UUID.randomUUID().toString();
    try {
      try (ArchiveStore store = new ArchiveStore(context)) {
        ArchiveStore.Stats stats =
            store.importFile(
                input, true, "fictional.zip", firstSource, new ArchiveImporter.Control());
        assertEquals(2, stats.newAssets);
        assertEquals(4, stats.assetReferences);
        assertEquals(0, stats.unavailableAssets);
        assertEquals(2, count(store, "assets"));
        assertEquals(4, count(store, "message_assets"));
        assertEquals(2, new File(context.getFilesDir(), "nova-archive-assets").list().length);
        ArchiveStore.Stats duplicate =
            store.importFile(
                input,
                true,
                "fictional.zip",
                UUID.randomUUID().toString(),
                new ArchiveImporter.Control());
        assertEquals(0, duplicate.newAssets);
        assertEquals(0, duplicate.updatedAssets);
        assertEquals(2, duplicate.skippedAssets);
        assertEquals(0, duplicate.newConversations);
        assertEquals(0, duplicate.newMessages);
        assertEquals(stats.assetStorageBytes, duplicate.assetStorageBytes);
        try (Cursor q =
            store
                .getReadableDatabase()
                .rawQuery("SELECT first_source,latest_source FROM assets", null)) {
          while (q.moveToNext()) {
            assertEquals(firstSource, q.getString(0));
            assertNotEquals(firstSource, q.getString(1));
          }
        }
      }
      assertTrue(input.delete());
      try (ArchiveStore reopened = new ArchiveStore(context)) {
        assertEquals(2, reopened.getReadableDatabase().getVersion());
        assertEquals(4, count(reopened, "message_assets"));
        try (Cursor q =
            reopened
                .getReadableDatabase()
                .rawQuery("SELECT relative_path,bytes,detected_mime,state FROM assets", null)) {
          while (q.moveToNext()) {
            assertEquals("complete", q.getString(3));
            assertEquals(
                q.getLong(1),
                ArchiveAssetFiles.resolve(
                        new File(context.getFilesDir(), "nova-archive-assets"), q.getString(0))
                    .length());
          }
        }
      }
    } finally {
      input.delete();
    }
  }

  @Test
  public void allSupportedTypesPersistAndProviderUsesDetectedMime() throws Exception {
    File input = File.createTempFile("fictional-types-", ".zip", context.getCacheDir());
    try (OutputStream out = new FileOutputStream(input)) {
      out.write(ArchiveAssetFixtures.allTypes());
    }
    long row;
    try (ArchiveStore store = new ArchiveStore(context)) {
      ArchiveStore.Stats stats =
          store.importFile(
              input,
              true,
              "fictional.zip",
              UUID.randomUUID().toString(),
              new ArchiveImporter.Control());
      assertEquals(5, stats.newAssets);
      assertEquals(5, stats.assetReferences);
      assertEquals(0, stats.unavailableAssets);
      row = store.list("", false, 10).get(0).id;
    } finally {
      assertTrue(input.delete());
    }
    try (ArchiveStore reopened = new ArchiveStore(context)) {
      java.util.Map<String, ArchiveAsset> assets = reopened.assets(row);
      String[] ids = {
        ArchiveAssetFixtures.IMAGE,
        ArchiveAssetFixtures.JPEG,
        ArchiveAssetFixtures.DOC,
        ArchiveAssetFixtures.PDF,
        ArchiveAssetFixtures.SHEET
      };
      String[] mimes = {
        "image/png", "image/jpeg", ArchiveAssetFiles.DOCX, "application/pdf", ArchiveAssetFiles.XLSX
      };
      for (int i = 0; i < ids.length; i++) {
        ArchiveAsset a = assets.get(ids[i]);
        assertNotNull(a);
        assertTrue(a.available());
        assertEquals(mimes[i], a.mime);
        android.net.Uri uri =
            androidx.core.content.FileProvider.getUriForFile(
                context, context.getPackageName() + ".archiveassets", a.file);
        assertEquals(mimes[i], context.getContentResolver().getType(uri));
        try (InputStream in = context.getContentResolver().openInputStream(uri)) {
          assertNotNull(in);
          long bytes = 0;
          byte[] buffer = new byte[4096];
          int n;
          while ((n = in.read(buffer)) != -1) bytes += n;
          assertEquals(a.bytes, bytes);
        }
      }
      ArchiveModel.Conversation c = reopened.load(row);
      String html =
          ArchiveRenderer.html(
              c, ArchiveTree.select(c, false), assets, ArchiveRenderer.AssetMode.PORTABLE);
      assertTrue(html.contains("data:image/png;base64,"));
      assertTrue(html.contains("data:image/jpeg;base64,"));
      assertTrue(html.contains("fictional.pdf"));
      assertTrue(html.contains("fictional.xlsx"));
      assertTrue(html.contains("fictional.docx"));
    }
  }

  @Test
  public void nativeImageRejectionPreservesVerifiedOldBinary() throws Exception {
    File good = input(false),
        bad = File.createTempFile("fictional-bad-image-", ".zip", context.getCacheDir());
    java.util.Map<String, byte[]> entries = new java.util.LinkedHashMap<>();
    try (java.util.zip.ZipInputStream in =
        new java.util.zip.ZipInputStream(new FileInputStream(good))) {
      java.util.zip.ZipEntry e;
      while ((e = in.getNextEntry()) != null) {
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        byte[] b = new byte[4096];
        int n;
        while ((n = in.read(b)) != -1) bytes.write(b, 0, n);
        entries.put(e.getName(), bytes.toByteArray());
      }
    }
    byte[] rejected = ArchiveAssetFixtures.image("png");
    // Corrupt IHDR CRC: header detector can see dimensions; native codec rejects it.
    rejected[29] ^= 0x55;
    android.graphics.BitmapFactory.Options options = new android.graphics.BitmapFactory.Options();
    options.inJustDecodeBounds = true;
    android.graphics.BitmapFactory.decodeByteArray(rejected, 0, rejected.length, options);
    assertTrue(options.outWidth <= 0 || options.outHeight <= 0);
    entries.put("wrapper/" + ArchiveAssetFixtures.IMAGE + ".dat", rejected);
    try (OutputStream out = new FileOutputStream(bad)) {
      out.write(ArchiveAssetFixtures.zip(entries));
    }
    try (ArchiveStore store = new ArchiveStore(context)) {
      store.importFile(
          good, true, "fictional.zip", UUID.randomUUID().toString(), new ArchiveImporter.Control());
      long row = store.list("", false, 1).get(0).id;
      ArchiveAsset before = store.assets(row).get(ArchiveAssetFixtures.IMAGE);
      store.importFile(
          bad, true, "fictional.zip", UUID.randomUUID().toString(), new ArchiveImporter.Control());
      ArchiveAsset after = store.assets(row).get(ArchiveAssetFixtures.IMAGE);
      assertTrue(after.available());
      assertEquals(before.file, after.file);
      assertEquals(before.bytes, after.bytes);
      assertEquals(2, new File(context.getFilesDir(), "nova-archive-assets").list().length);
    } finally {
      good.delete();
      bad.delete();
    }
  }

  @Test
  public void malformedReimportAndCancellationPreserveExistingArchive() throws Exception {
    File good = input(false), bad = input(true);
    try (ArchiveStore store = new ArchiveStore(context)) {
      store.importFile(
          good, true, "fictional.zip", UUID.randomUUID().toString(), new ArchiveImporter.Control());
      assertEquals(
          "A04_JSON_PARSE_FAILED",
          assertThrows(
                  ArchiveError.class,
                  () ->
                      store.importFile(
                          bad,
                          true,
                          "fictional.zip",
                          UUID.randomUUID().toString(),
                          new ArchiveImporter.Control()))
              .code);
      ArchiveImporter.Control cancel = new ArchiveImporter.Control();
      cancel.cancelled.set(true);
      assertEquals(
          "A07_IMPORT_CANCELLED",
          assertThrows(
                  ArchiveError.class,
                  () ->
                      store.importFile(
                          good, true, "fictional.zip", UUID.randomUUID().toString(), cancel))
              .code);
      assertEquals(2, count(store, "assets"));
      assertEquals(4, count(store, "message_assets"));
      assertEquals(2, new File(context.getFilesDir(), "nova-archive-assets").list().length);
    } finally {
      good.delete();
      bad.delete();
    }
  }

  @Test
  public void archiveDeletionRemovesPrivateBinariesButRetainsExternalTestFile() throws Exception {
    File zip = input(false),
        external = File.createTempFile("fictional-external-", ".html", context.getCacheDir());
    try {
      try (ArchiveStore store = new ArchiveStore(context)) {
        store.importFile(
            zip,
            true,
            "fictional.zip",
            UUID.randomUUID().toString(),
            new ArchiveImporter.Control());
      }
      assertTrue(ArchiveStore.deleteArchive(context));
      assertFalse(context.getDatabasePath(ArchiveStore.DATABASE).exists());
      assertFalse(new File(context.getFilesDir(), "nova-archive-assets").exists());
      assertFalse(new File(context.getFilesDir(), "nova-archive-pending").exists());
      assertTrue(external.exists());
    } finally {
      zip.delete();
      external.delete();
    }
  }

  @Test
  public void schemaOneUpgradePreservesConversationAndRecoversAssetsOnReimport() throws Exception {
    File input = input(false);
    try {
      try (ArchiveStore store = new ArchiveStore(context)) {
        store.importFile(
            input,
            true,
            "fictional.zip",
            UUID.randomUUID().toString(),
            new ArchiveImporter.Control());
        store.getWritableDatabase().execSQL("DROP TABLE message_assets");
        store.getWritableDatabase().execSQL("DROP TABLE assets");
        store.getWritableDatabase().setVersion(1);
      }
      try (ArchiveStore upgraded = new ArchiveStore(context)) {
        assertEquals(2, upgraded.getReadableDatabase().getVersion());
        assertEquals(1, count(upgraded, "conversations"));
        assertEquals(0, count(upgraded, "assets"));
        ArchiveStore.Stats restored =
            upgraded.importFile(
                input,
                true,
                "fictional.zip",
                UUID.randomUUID().toString(),
                new ArchiveImporter.Control());
        assertEquals(0, restored.newConversations);
        assertEquals(0, restored.newMessages);
        assertEquals(2, restored.newAssets);
        assertEquals(4, count(upgraded, "message_assets"));
      }
    } finally {
      input.delete();
    }
  }

  @Test
  public void restartCleansUncommittedFilesWhileRetainingCommittedOnes() throws Exception {
    File input = input(false);
    try {
      try (ArchiveStore store = new ArchiveStore(context)) {
        store.importFile(
            input,
            true,
            "fictional.zip",
            UUID.randomUUID().toString(),
            new ArchiveImporter.Control());
      }
      File root = new File(context.getFilesDir(), "nova-archive-assets"),
          orphan = new File(root, UUID.randomUUID() + ".bin");
      try (OutputStream out = new FileOutputStream(orphan)) {
        out.write(1);
      }
      File pending = new File(context.getFilesDir(), "nova-archive-pending/" + UUID.randomUUID());
      assertTrue(pending.mkdirs());
      try (OutputStream out = new FileOutputStream(new File(pending, UUID.randomUUID() + ".bin"))) {
        out.write(2);
      }
      try (ArchiveStore reopened = new ArchiveStore(context)) {
        assertEquals(2, count(reopened, "assets"));
        assertFalse(orphan.exists());
        assertFalse(pending.exists());
        assertEquals(2, root.list().length);
      }
    } finally {
      input.delete();
    }
  }
}
